[package]
name = "structsToStructureRelatedData"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock"] }
uuid = { version = "1.14", features = ["v4"] }
